
/**
 * Home constants for all features.
 */
export class PageConstants {
  /**
   * Constants on the tab page of the main interface.
   */
  static readonly CURRENT_INDEX: number = 0;                    // 当前下标
  static readonly TAB_BAR_FIRST: number = 0;                    // 第一个Tab页
  static readonly TAB_BAR_SECOND: number = 1;                   // 第二个Tab页
  static readonly TAB_BAR_THIRD: number = 2;                    // 第三个Tab页
  static readonly TAB_BAR_FOURTH: number = 3;                   // 第四个Tab页
  static readonly TAB_BAR_FIFTH: number = 4;                    // 第五个Tab页
  static readonly TAB_BAR_SIXTH: number = 5;                    // 第六个Tab页
  static readonly TAB_BAR_SEVENTH: number = 6;                  // 第七个Tab页
  static readonly TAB_BAR_EIGHTH: number = 7;                   // 第八个Tab页

  static readonly BAR_WIDTH: number = 360;                      // Tab栏宽度
  static readonly BAR_HEIGHT: number = 60;                      // Tab栏高度
  static readonly FONT_WEIGHT_SELECT: number = 500;             // 选中字体大小
  static readonly FONT_WEIGHT_UNSELECT: number = 400;           // 未选中字体大小
  static readonly LINE_HEIGHT: number = 22;                     //
  static readonly MARGIN_TOP_TWO: number = 17;                  // 外边距-上
  static readonly MARGIN_BOTTOM: number = 7;                    // 外边距-下
  static readonly STROKE_WIDTH: number = 2;                     // 分割线宽度

  /**
   * 图像列表常量
   */
  static readonly COLUMN_WIDTH: string = '86.7%';
  static readonly LIST_SPACE: number = 20;
  static readonly LIST_INITIAL_INDEX: number = 0;
  static readonly IMAGE_HEIGHT: string = '84.8%';
  static readonly IMAGE_WIDTH: string = '26.7%';
  static readonly DIVIDER_STROKE_WIDTH: number = 1;
  static readonly LIST_ITEM_ROW_COLUMN_WIDTH: string = '73.3%';
  static readonly LIST_ITEM_ROW_HEIGHT: string = '12.3%';
  static readonly WIDTH: number = 720;
  static readonly HEIGHT: number = 720;

  /**
   * 扫描按钮尺寸
   */
  static readonly TAB_BUTTON_HEIGHT: string = '51%';
  static readonly TAB_COLUMN_HEIGHT: string = '10%';
}